SELECT 
      M.PROVINCECODE,
      SUBSTR(TO_CHAR(T.TRANDATE), 1, 6) AS TRANDATE_MONTH,
      COUNT(*) AS TRANSACTION_COUNT,
      SUM(T.AMOUNT) AS AMOUNT_SUM,
      COUNT(DISTINCT T.PAN) AS UNIQUE_CARDS

FROM 
    TB_TRANSACTIONS T
JOIN 
    TB_MERCHANTS M ON T.TERMINALNO = M.TERMINAL_NO

GROUP BY 
        SUBSTR(TO_CHAR(T.TRANDATE), 1, 6),
        M.PROVINCECODE
         
ORDER BY 
        SUBSTR(TO_CHAR(T.TRANDATE), 1, 6),
        M.PROVINCECODE