SELECT 
    M.TERMINAL_NO,
    COUNT(AMOUNT),
    COUNT(CASE WHEN T.TRANTYPE = 00 THEN 1 END) AS PURCHASE_TRAN,
    COUNT(CASE WHEN T.TRANTYPE = 31 THEN 1 END) AS BALANCE_TRAN,
    COUNT(CASE WHEN T.TRANTYPE = 50 THEN 1 END) AS CHARGE_TRAN,
    SUM(T.AMOUNT) AS TOTAL_SUM,
    SUM(T.VOUCHERAMOUNT) AS TOTAL_VOUCHER
FROM 
    TB_MERCHANTS M
    
LEFT JOIN 
    TB_TRANSACTIONS T ON T.TERMINALNO = M.TERMINAL_NO
    AND SUBSTR(TO_CHAR(T.TRANDATE), 1, 6) = '140110'
GROUP BY 
    M.TERMINAL_NO
ORDER BY 
    M.TERMINAL_NO