SELECT 
    T.TERMINALNO, 
    COUNT(*) AS TOTAL_TRANSACTIONS
FROM (
    SELECT 
        TERMINALNO, COUNT(*)
    FROM 
        TB_TRANSACTIONS
    WHERE 
        SUBSTR(TRANDATE, 1, 6) = '140110'
    GROUP BY 
        TERMINALNO
    HAVING 
        COUNT(TERMINALNO) >= 2
) D
JOIN 
    TB_TRANSACTIONS T ON D.TERMINALNO = T.TERMINALNO
WHERE 
    SUBSTR(T.TRANDATE, 1, 6) = '140111'
GROUP BY 
    T.TERMINALNO
ORDER BY 
    T.TERMINALNO